In [20]:
import yaml
import pandas as pd
import numpy as np
from colour import hex2hsl 

pd.set_option('display.max_rows', None)  # Print all rows
pd.set_option('display.max_columns', None)  # Print all columns
pd.set_option('display.width', None)  # Allow wide display
pd.set_option('display.max_colwidth', -1) 

with open('/home/zampinojosh/src/hub/twc-flask/storage/db_iching_data.yaml', 'r') as file:
    data = yaml.safe_load(file)


/tmp/ipykernel_15275/544351551.py:9: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [21]:
for hexagram in data["hexagrams"]:
        hexagram["decimal"] = int(hexagram["binary"], 2)
        #print(hexagram["decimal"] )

for trigram in data["trigrams"]:
        trigram["decimal"] = int(trigram["binary"],2)
        #print(trigram["decimal"])



In [23]:
# Create a matrix where each row contains the row number
lower = np.arange(0, 8).reshape(8, 1) * np.ones((1, 8))

# Create a matrix where each row contains the numbers 1 to 8
upper = np.tile(np.arange(0, 8), (8, 1))

        


colors_hex = {
    0: "#FFFFFF",  # White
    1: "#FF0000",  # Red
    2: "#00FF00",  # Green
    3: "#0000FF",  # Blue
    4: "#FFFF00",  # Yellow
    5: "#00FFFF",  # Cyan
    6: "#FF00FF",  # Magenta
    7: "#000000"   # Black
}



print(lower)
print(upper)


{0: 0.0, 1: 0.0, 2: 0.33333333333333337, 3: 0.6666666666666666, 4: 0.16666666666666663, 5: 0.5, 6: 0.8333333333333334, 7: 0.0}
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7.]]
[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]
